version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    links:
      - proba-database
    volumes:
      - ./:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    networks:
      - app-network

  proba-database:
    image: mysql
    volumes:
      - ./database:/var/lib/mysql
    restart: always
#        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    environment:
      - MYSQL_ROOT_PASSWORD=password
    container_name: proba-database
    ports:
      - 3306:3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge